-------------------------------------------------------------------------------
Test set: io.cloudboost.CloudUserTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.974 sec <<< FAILURE!
createNewUser(io.cloudboost.CloudUserTest)  Time elapsed: 1.971 sec  <<< FAILURE!
junit.framework.AssertionFailedError: {"error":"No Table found."}
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudUserTest$1.done(CloudUserTest.java:29)
	at io.cloudboost.CloudUser.signUp(CloudUser.java:145)
	at io.cloudboost.CloudUserTest.createNewUser(CloudUserTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
